services:
  projetomedicaoautomatica-api-java:
    image: projetomedicaoautomatica-api-java:latest
    build:
      dockerfile: Dockerfile
    environment:
      DATA_BASE_URL: "jdbc:mysql://guide-mysql:3306/projetomedicaoautomatica"
      DATA_BASE_USERNAME: "myuser"
      DATA_BASE_PW: "secret"
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql

  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=projetomedicaoautomatica'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'